services:
  frontend:
    build: .
    container_name: livrer-nourriture-frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.livrernourriture-fibem.com/api/v1
    networks:
      # - app-network
      - livraison-nourriture_app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`app.livrernourriture-fibem.com`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=le"
      - "traefik.http.services.front.loadbalancer.server.port=3070"

networks:
  livraison-nourriture_app-network:
    external: true
  # app-network:
  #   external: true